<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-05-22 22:18
=======
# Generated by Django 3.2.13 on 2022-05-15 18:49
>>>>>>> 319da7cfb894e39058db0c1afa1dc5dcd5699b25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='SecretKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255, unique=True)),
                ('add_secret', models.DateTimeField(auto_now=True)),
                ('expiry_secret', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=25, unique=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
=======
            name='BioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
>>>>>>> 319da7cfb894e39058db0c1afa1dc5dcd5699b25
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
