# Generated by Django 3.2.13 on 2022-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biouser',
            name='id_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biouser',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='religion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
