# Generated by Django 3.2.13 on 2022-05-18 14:53

import array
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_alter_navuser_nav_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navuser',
            name='nav_name',
            field=models.JSONField(default=array.array),
        ),
    ]
