# Generated by Django 3.2.13 on 2022-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_alter_navuser_nav_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biouser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
