# Generated by Django 3.2.13 on 2022-05-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20220519_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biouser',
            name='custom_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='gender',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='id_number',
            field=models.CharField(max_length=255),
        ),
    ]
