# Generated by Django 3.2.13 on 2022-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_auto_20220519_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biouser',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
