# Generated by Django 3.2.13 on 2022-05-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_navuser_nav_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navuser',
            name='nav_name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
