# Generated by Django 3.2.13 on 2022-05-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_alter_navuser_nav_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavUser',
        ),
    ]
