# Generated by Django 3.2.13 on 2022-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_secretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretkey',
            name='add_secret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='secretkey',
            name='expiry_secret',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='secretkey',
            name='secret_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
