# Generated by Django 3.2.13 on 2022-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_auto_20220520_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretkey',
            name='expiry_secret',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
