# Generated by Django 3.2.13 on 2022-04-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField()),
                ('selling', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('update', models.DateField(auto_now=True)),
                ('descriptions', models.TextField()),
                ('slugProduct', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
