# Generated by Django 3.2.13 on 2022-04-22 16:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_auto_20220420_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
