# Generated by Django 3.2.13 on 2022-04-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_alter_product_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
