# Generated by Django 3.2.13 on 2022-04-29 07:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_remove_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('note', ckeditor.fields.RichTextField(null=True)),
                ('slugPO', models.SlugField(editable=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.suplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.product')),
            ],
        ),
    ]
