# Generated by Django 3.2.13 on 2022-05-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0007_auto_20220429_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slugProduct',
        ),
        migrations.RemoveField(
            model_name='suplier',
            name='slugSuplier',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='suplier',
            name='suplier_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
