# Generated by Django 3.2.13 on 2022-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0008_auto_20220514_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='custom_id',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='purchase_id',
            new_name='custom_id',
        ),
        migrations.RenameField(
            model_name='suplier',
            old_name='suplier_id',
            new_name='custom_id',
        ),
        migrations.AlterField(
            model_name='suplier',
            name='suplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
