# Generated by Django 3.2.13 on 2022-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0009_auto_20220514_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='custom_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='custom_id',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
