# Generated by Django 3.2.13 on 2022-05-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0010_auto_20220515_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
