# Generated by Django 3.2.13 on 2022-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0011_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
