# Generated by Django 3.2.13 on 2022-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0013_auto_20220515_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='doc_type',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
