# Generated by Django 3.2.13 on 2022-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0014_auto_20220515_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
