# Generated by Django 3.2.13 on 2022-05-18 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0015_auto_20220516_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default='', null=True),
        ),
    ]
