# Generated by Django 3.2.13 on 2022-05-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0019_alter_product_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='custom_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='doc_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='custom_id',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
